export const TOKEN_KEY = 'github-access-token-v1'
export const TAB_KEY = 'github-access-tab-v1'
export const ORG_FILTER_KEY = 'github-access-org-filter-v1'
export const PERSONAL_SELF_KEY = '__personal_self'
export const PERSONAL_OTHER_KEY = '__personal_other'
export const REPO_FILTER_KEY = 'github-access-repo-filter-v1'
export const REPO_FILTERS_KEY = 'github-access-repo-filters-v1'
